// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  untilEOL = 93,
  Program = 1,
  LocalDeclaration = 2,
  GlobalConstantDeclaration = 3,
  AttributeList = 4,
  Attribute = 5,
  Identifier = 6,
  IntLiteral = 7,
  UintLiteral = 8,
  FloatLiteral = 9,
  Keyword = 88,
  VariableIdentifier = 11,
  TypeDeclaration = 12,
  Type = 86,
  Assign = 87
